version: 2

jobs:
  test:
    parallelism: 1
    working_directory: ~/repo
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          key: repo-{{ .Branch }}-2
      - run: npm ci
      - save_cache:
          key: repo-{{ .Branch }}-2-{{ checksum "package.json" }}
          paths:
            - ~/.npm
      - run: npm run build
      - run: npm test
      - run: npm run size
      - run: npm run semantic-release || true

workflows:
  version: 2
  test:
    jobs:
      - test
